- name: Install Apache2 package
  hosts: localhost
  become: true
  become_method: sudo
  environment:
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  tasks:
    - name: Install Apache2
      apt:
        name: apache2
        state: present

