---
- name: Install HTTPD Server
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Install httpd package
      package:
        name: httpd
        state: present
    - name: Start and enabling httpd
      service:
        name: httpd
        state: started
        enabled: true

