---
- name: Install Apache2 package
  hosts: localhost
  become: true
  become_user: admin
  tasks:
    - name: Install Apache2
      apt:
        name: apache2
        state: present
      become: yes
      become_user: admin
      vars:
        ansible_become_password: "12345"
