---
- name: Stop GCP VM
  hosts: all  
  become: true  
  tasks:
    - name: Install required Python packages
      become: true
      become_user: sa_114966270712069978938
      pip:
        name: "{{ item }}"
      with_items:
        - google-auth
        - google-auth-oauthlib
        - google-auth-httplib2
    - name: Stop GCP VM
      gcp_compute_instance:
        state: "absent"
        project: "sinuous-tuner-414107"
        zone: "us-west1-b"
        auth_kind: "serviceaccount"
        service_account_file: "/home/sa_114966270712069978938/keys.json"
