---
- name: Install, Start, and Enable Apache (httpd) on RHEL using Yum
  hosts: all  # Specify the target host or group
  become: true  # Run tasks with elevated privileges (sudo)

  tasks:
    - name: Install httpd (Apache) using yum
      yum:
        name: httpd
        state: present

    - name: Start httpd service
      service:
        name: httpd
        state: started
        enabled: yes
        

