---
- name: Install, Start, and Enable Apache (httpd) on RHEL using Yum
  hosts: all  # Specify the target host or group
  become: true  # Run tasks with elevated privileges (sudo)

  tasks:
    - name: Install httpd (Apache) using yum
      package:
        name: nginx
        state: present

    - name: Start httpd service
      service:
        name: nginx
        state: started
        enabled: yes
# ---        
# - name: stopping the vm 
#   hosts: all
#   become: true
#   gather_facts: false 
#   vars:
#     gcp_project: "sinuous-tuner-414107"
#     gcp_auth_kind: "serviceaccount"  # Replace with your GCP authentication method
#     # gcp_credentials_file: "./keys.json"  # Replace with the path to your GCP service account key file
#     gcp_zone: "us-west1-b"  # Replace with your GCP zone
#     gcp_instance_name: "34.168.204.111"  # Replace with your GCP instance name
#   tasks:
#     - name: Install google-auth library
#       pip:
#         name: google-auth
#     - name: Stop GCP VM
#       gcp_compute_instance:
#         project: "{{ gcp_project }}"
#         auth_kind: "{{ gcp_auth_kind }}"
#         # service_account_file: "{{ gcp_credentials_file }}"
#         zone: "{{ gcp_zone }}"
#         instance_names: "{{ gcp_instance_name }}"
#         state: "absent"
