---
- name: Install Apache Web Server
  hosts: all
  become: true  # Run tasks with sudo

  tasks:
    - name: Check OS Distribution
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - '!min'

    - name: Install Apache2 on Ubuntu
      ansible.builtin.package:
        name: apache2
        state: present
      when: "'Ubuntu' in ansible_distribution"

    - name: Install httpd on CentOS
      ansible.builtin.yum:
        name: httpd
        state: present
        use_backend: dnf  # Explicitly specify the backend for CentOS 8 and later

    - name: Start and enable httpd service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true
