# ---
# - name: Install, Start, and Enable Apache (httpd) on RHEL using Yum
#   hosts: all  # Specify the target host or group
#   become: true  # Run tasks with elevated privileges (sudo)

#   tasks:
#     - name: Install httpd (Apache) using yum
#       package:
#         name: apache2
#         state: present

#     - name: Start httpd service
#       service:
#         name: apache2
#         state: started
#         enabled: yes
---
- name: Stop GCP VM
  hosts: all  # Specify the target host or group
  become: true  # Run tasks with elevated privileges (sudo)
  gcp_compute_instance:
    name: "34.168.204.111"
    state: "absent"
    project: "sinuous-tuner-414107"
    zone: "us-west1-b"
    auth_kind: "serviceaccount"
    service_account_file: "/home/sa_114966270712069978938/keys.json"
    wait_for_instances: true  # Optional, waits for the instances to stop
